<?php include 'header.php';?>
<!-- Start body -->
<section class="head-sec gradient-bg">
	<div class="container">
		<h1>Privacy Policy</h1>
	</div>
</section>
<section class="section-setting">
	<div class="container" style="max-width: 1000px;">
		<div class="text-row">
			<p><b>This Privacy Notice was last modified: June 18, 2020</b></p>
		</div>
		<div class="text-row">
			<!-- <h4>Where does it come from?</h4>
			<div class="highlight">
				<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock.</p>
				<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form</p>
			</div> -->
			<p>It is the policy of INNOVATE1 Services to protect and preserve the privacy of its clients, users and customers and the confidentiality of the Information they provide, subject to conditions described below. To demonstrate our commitment to privacy we encourage all of our current and prospective users to read this Privacy Policy carefully before using this site and our services. By using this site ( <a href="https://www.innovate1services.com">www.innovate1services.com</a> ) and the associated services, You acknowledge reading and accepting this Privacy Policy and all accompanied Terms of Use. INNOVATE1 Services reserves the right to expand and/or modify this Privacy Policy at any time.</p>
		</div>
		<div class="text-row">
			<h4>The Privacy Policy</h4>
			<p>This Privacy Policy ("Privacy Policy") applies to INNOVATE1 Services its parents and related entities, subsidiaries, whether or not wholly owned (collectively the "INNOVATE1 Services") and specifically, it outlines the types of Information that INNOVATE1 Services gathers, uses, and shares about you ("You" or "User") when You are visit the INNOVATE1 Services website, located at <a href="https://www.innovate1services.com">https://www.innovate1services.com</a>, (the "INNOVATE1 Services Website(s)"). This Privacy Policy is incorporated into and is subject to the INNOVATE1 Services Terms of Use. Your use of the INNOVATE1 Services Website and any personal Information You provide on the INNOVATE1 Services Website remains subject to the terms of this Privacy Policy and our Terms of Use. This Privacy Policy does not apply to information collected by INNOVATE1 Services offline or to third party websites, applications, or services (including our affiliates).</p>
		</div>
		<div class="text-row">
			<h4>Contact Information</h4>
			<p>Should you have any comments or questions about how we collect and use your personal information, communications can be directed to INNOVATE1 Services via email to <a href="mailto:info@innovate1services.com">info@innovate1services.com</a>.</p>
		</div>
		<div class="text-row">
			<h4>Applicability & Eligibility</h4>
			<p>Before accessing, using, or interacting with the INNOVATE1 Services Websites you should carefully review the terms and conditions of this Privacy Policy. Your use of the INNOVATE1 Services Websites is further governed by our Terms of Use available at <a href="https://www.innovate1services.com/cms/termsOfUse">https://www.innovate1services.com/cms/termsOfUse</a> and incorporated into this agreement by this reference.</p>
			<p>The INNOVATE1 Services Websites are not directed to children under the age of 18. You may not use the INNOVATE1 Services Websites if you are under the age of 18. If you are under the age of 18, you should not provide any information on our INNOVATE1 Services Websites.</p>
		</div>
		<div class="text-row">
			<h4>Information Collection & Use</h4>
			<p>INNOVATE1 Services collects information about you and your use of the INNOVATE1 Services Websites, including, but not limited to, when you provide information to us in connection with the INNOVATE1 Services Websites and when we automatically collect information about you when you access, use, or interact with the INNOVATE1 Services Websites. Such processing is performed to provide the Website to you. By accepting our Privacy Policy and Terms of Use, you are confirming you have read and understand our policies including how and why we use your information.</p>
			<p>The types of information INNOVATE1 Services may collect about you include:</p>
		</div>
		<div class="text-row">
			<h4>Information You Provide to Us:</h4>
			<p>We process information you provide to us on the legal basis of INNOVATE1 Services legitimate interest in performing the function or services you requested. Where appropriate, we may rely on alternate legal bases, such as your consent to certain types of processing. You may refuse to supply any of the following information, however, it may prevent you from accessing certain INNOVATE1 Services Website areas and features.</p>
			<p><b>Account Information:</b> Users may register for an account (a "Website Account"). We do not require you to register to use the INNOVATE1 Services Websites. However, if you do register a Website Account, you will gain access to those areas and features of the INNOVATE1 Services Website that require registration. INNOVATE1 Services will collect certain information about you in connection with your registration for a Website Account, which may include personal data such as information regarding your name, debit or credit card number, card verification number, card expiration number, address, telephone number and email address and other information you may provide such as username and password.</p> 
			<p><b>Payment Transaction Information:</b> We may collect and store information related to purchases or payments made through the INNOVATE1 Services Website. You may provide certain information to complete or receive payments via the INNOVATE1 Services Website, including your  bank account number, credit or debit card number, card expiration date, CVV code, and may require a personal address, business category and other Information (collectively, "Payment Information") necessary to complete payment transactions through certain services. This Information is stored within your INNOVATE1 Services Website Account.</p>
			<p>Note that INNOVATE1 Services works with Service Providers (as defined below) to handle payment transactions. This information is handled for INNOVATE1 Services by our Service Providers. You are subject to the Privacy Policies and Terms and Conditions of our Service Providers when utilizing a third party service through the INNOVATE1 Services Website. Please review the Service Providers’ Privacy Policies and Terms and Conditions before using their services</p>
			<p><b>Correspondence Information:</b> If you subscribe to our mailing list or email us, we may keep your message, email address, and contact information to respond to your requests, provide the requested products or INNOVATE1 Services Website, and to provide notifications or other correspondences to you. We do not share or sell any personal information to other organizations for commercial purposes. If you do not want to receive communications from us in the future, please let us know by sending us an e-mail requesting the same to  <a href="mailto:tmahoney@innovate1services.com">tmahoney@innovate1services.com</a> or by following the unsubscribe instructions found in any e-mail we send. If you supply us with your postal address on-line, you may receive periodic mailings from us with information on new products and services or upcoming events. If you do not wish to receive such mailings, please let us know by contacting us at <a href="mailto:tmahoney@innovate1services.com">tmahoney@innovate1services.com</a> or by calling our phone number provided above. Please note, requests to remove your email address from our lists may take some time to fulfil. We may also still contact you as needed to provide important announcements or notifications regarding the Website.</p>
			<p><b>Support Information:</b> You may provide information to us via a support request submitted through the INNOVATE1 Services Website. We will use this information to assist you with your support request and may maintain this information to assist you or other Users with support requests. Please do not submit any information to us via a support submission, including confidential or sensitive information that you do not wish for INNOVATE1 Services or our Service Providers to have access to or use in the future.</p>
			<p><b>Form Information:</b> We may use forms to request certain information from you on the INNOVATE1 Services Website, such as your contact information to assist with contacts or service requests. This information may include personal data.</p>
		</div>
		<div class="text-row">
			<h4>Information We Collect Automatically:</h4>
			<p>We use automatic data collection and analytics technologies to collect aggregate and user-specific information about your equipment, domain name, patterns of use, communication data, and the resources that you access and use on the INNOVATE1 Services Website, including your IP address, browsing and navigation patterns. This information is used to improve our INNOVATE1 Services Websites. We process information collected automatically on the legal basis of INNOVATE1 Services legitimate interest in assessing the us of its INNOVATE1 Services Websites. Information we collect automatically through our use of the Website Includes:</p>
			<p><b>Cookies, Web Beacons, Links, And Other Tracking Technologies:</b> INNOVATE1 Services may keep track of how you use and interact with the INNOVATE1 Services Website through the use of cookies, web beacons, links, and other tracking technologies.  We do this to help analyse the use of and improve the Website. Through these technologies we may automatically collect information about your use of the INNOVATE1 Services Website and other online activities, including our email correspondences, third-party services, and client applications, and certain online activities after you leave the INNOVATE1 Services Website. Link information is generally only analysed on an aggregate basis. Some Website features may not function properly if you disable cookies. Such data may include analytics information, sites visited before visiting the Website, browser type, operating system, and tracking of your interactions with our content and emails.</p>
			<p>We partner with third parties to manage our advertising on other sites. Our third-party partners may use cookies or similar technologies in order to provide you with advertising based upon your browsing activities and interests.</p>
			<p><b>Unique Identifiers:</b> When you use or access the INNOVATE1 Services Website, we may access, collect, monitor, store on your device, and/or remotely store one or more "Unique Identifiers," such as a universally unique identifier ("UUID"). A Unique Identifier may remain on your device persistently, to help you log in faster and enhance your navigation through the INNOVATE1 Services Website. Some features of the Website may not function properly if use or availability of Unique Identifiers is impaired or disabled.</p>
			<p><b>Analytics Information:</b> We use data analytics to ensure site functionality and improve the INNOVATE1 Services Website. We use mobile analytics software to allow us to understand the functionality of the INNOVATE1 Services Website on your phone. This software may record information such as how often you use the Website, what happens within the INNOVATE1 Services Website, aggregated usage, performance data, app errors and debugging information, and where the INNOVATE1 Services Website was downloaded from. We do not link the information we store within the analytics software to any personally identifiable information that you submit within the mobile application.</p>
			<p><b>Log File Information:</b> When you use the INNOVATE1 Services Website, we may receive log file information such as your IP address, browser type, access times, domain names operating system, the referring web page(s), pages visited, location, your mobile carrier, device information (including device and application IDs), search terms, and cookie information. We receive log file data when you interact with our INNOVATE1 Services Website, for example, when you visit our INNOVATE1 Services Website, sign into our INNOVATE1 Services Website, or interact with our email notifications. INNOVATE1 Services uses log file data to provide, understand, and improve our INNOVATE1 Services Website, and to customize the content we show you. INNOVATE1 Services may link this log file to other information INNOVATE1 Services collects about you via the INNOVATE1 Services Website.</p>
			<p><b>Public Information:</b> INNOVATE1 Services may also collect information about you from publicly available sources. Information you make publicly available in any public or open forum, such as on a social network, may be considered public information for the purposes of this Privacy Policy, and may be accessed and collected by INNOVATE1 Services. Please be aware that any content or information you share with or provide to third parties using or related to your use of the INNOVATE1 Services Website is neither private, nor confidential. INNOVATE1 Services is not responsible for any content or information you post or share with third parties. If you do not wish for certain information to be public, please do not share it publicly.</p>
		</div>
		<div class="text-row">
			<h4>Third Party Information</h4>
			<p>We may obtain Information about You from third parties to protect You from fraud, financial misconduct, and to verify the Information You provided. </p>
		</div>
		<div class="text-row">
			<h4>Information Use </h4>
			<p>INNOVATE1 Services uses the information we receive about you for the purposes described in this Privacy Policy. We process personal data received about you through our INNOVATE1 Services Website on the legal basis of INNOVATE1 Services legitimate interest in providing the INNOVATE1 Services Website and their functionality to you. Such processing is necessary for the purposes of the legitimate interest pursued by INNOVATE1 Services or by our Affiliates related to the Website. Where appropriate, we may rely on alternate legal bases, such as your consent to certain types of processing.</p>
		</div>
		<div class="text-row">
			<h4>Information Sharing</h4>
			<p>When you access or use the INNOVATE1 Services Website, we collect, use, share, and otherwise process your personal information as described in this Privacy Policy. INNOVATE1 Services will not share, sell, rent, or otherwise disclose your private personal information to third parties without your consent, except in the limited circumstances described in this Privacy Policy, including to:</p>
			<p><b>Aggregated Non-Personal Data:</b> We may disclose aggregated, non-personal data received from providing the INNOVATE1 Services Website, including information that does not identify any individual, without restriction. INNOVATE1 Services may share demographic information with business partners, but it will be aggregated and de-personalized, so that personal information is not revealed.</p>
			<p><b>Within INNOVATE1 Services:</b> We may share and process information internally within INNOVATE1 Services and with our subsidiaries and affiliates. INNOVATE1 Services’ personnel may have access to your information as needed to provide and operate the INNOVATE1 Services Website in the normal course of business. This includes information regarding your use and interaction with the INNOVATE1 Services Website.</p>
			<p><b>Service Providers:</b> INNOVATE1 Services works with various organizations and individuals to help provide the Website to you ("Service Providers"), such as website and data hosting companies and companies providing analytics information, like Google Analytics. INNOVATE1 Services needs to engage such third-party Service Providers to help us operate, provide, and market the INNOVATE1 Services Website. These third parties have only limited access to your information and may use your information only to perform these tasks on our behalf. Information we share to our Service Providers may include both information you provide to us and information we collect about you, including personal data and information from data collection tools like cookies, web beacons, and log files.</p>
			<p>INNOVATE1 Services takes reasonable steps to ensure that our Service Providers are obligated to reasonably protect your information on INNOVATE1 Services’ behalf. If INNOVATE1 Services becomes aware that a Service Provider is using or disclosing information improperly, we will take commercially reasonable steps to end or correct such improper use or disclosure.</p>
			<p>We share personal information with our Service Providers on the legal basis of INNOVATE1 Services’ legitimate interests in providing you with the INNOVATE1 Services Website. Our engagement of Service Providers is often necessary for us to provide the INNOVATE1 Services Website to you, particularly where such companies play important roles like helping us keep our Website operating and secure. In some other cases, these service providers aren’t strictly necessary for us to provide the INNOVATE1 Services Website, but help us make it better, like by helping us conduct research into how we could better serve our Users. In these latter cases, we have a legitimate interest in working with service providers to make our INNOVATE1 Services Website better.</p>
			<p><b>Business Transactions:</b> INNOVATE1 Services may purchase other businesses or their assets, sell our business assets, or be involved in a bankruptcy, merger, acquisition, reorganization or sale of assets (a "Business Transaction"). Your information, including personal data, may be among assets sold or transferred as part of a Business Transaction.</p>
			<p><b>Safety and Lawful Requests:</b> We may be required to disclose Website user information pursuant to lawful requests, such as subpoenas or court orders, or in compliance with applicable laws. We generally do not disclose user information unless we have a good faith belief that an information request by law enforcement or private litigants meets applicable legal standards. We may share your information when we believe it is necessary to comply with applicable laws, to protect our interests or property, to prevent fraud or other illegal activity perpetrated through the INNOVATE1 Services Website or using the INNOVATE1 Services name, or to protect the safety of any person. This may include sharing information with other companies, lawyers, agents, or government agencies. Nothing in this Privacy Policy is intended to limit any legal defenses or objections that you may have to a third party’s, including a government’s, request to disclose your information. INNOVATE1 Services also reserves the right to disclose personally identifiable Information and/or non-personally identifiable Information that INNOVATE1 Services believes, in good faith, is appropriate or necessary in order to enforce the Terms of Use, take precautions against liability, investigate and defend itself against any third-party claims or allegations, assist government enforcement agencies, protect the security or integrity of the INNOVATE1 Services website, and to protect the rights, property, or personal safety of INNOVATE1 Services, our Users or others. In all cases we will treat requests to access Information or change Information in accordance with applicable legal requirements.</p>
			<p>Please do not send us any personal data if You do not consent to the transfer of this Information as outlined above.</p>
		</div>
		<div class="text-row">
			<h4>Transfer And Storage of Your Information</h4>
			<p>Please be advised information INNOVATE1 Services collects about you may be transferred, processed, and/or accessed by us in the United States or another country where we or our Service Providers operate. Please be aware that the privacy laws and standards in certain countries, including the rights of authorities to access your personal information, may differ from those that apply in the country in which you reside. If you are located outside the United States and choose to allow us to collect information about you, please be aware that INNOVATE1 Services may transfer your personal data to the United States and process and store it there. We will transfer personal information only to those countries to which we are permitted by law to transfer personal information, and we will take steps to ensure that your personal information continues to enjoy appropriate protections.</p> 
			<p>If you are located in the European Economic Area ("EEA") or other regions with laws governing data collection and use that may differ from U.S. law, please note that we may transfer information to a country or jurisdiction that does not have the same data protection laws as your jurisdiction, as disclosed in this Privacy Policy. It may also be processed by staff operating outside the EEA who work for us or for one of Service Providers, also as disclosed.</p>
		</div>
		<div class="text-row">
			<h4>Information Security</h4>
			<p>INNOVATE1 Services takes reasonable efforts to secure and protect the privacy, accuracy, and reliability of your information and to protect it from loss, misuse, unauthorized access, disclosure, alteration and destruction. INNOVATE1 Services implements security measures as we deem appropriate and consistent with industry standards. As no data security protocol is impenetrable, INNOVATE1 Services cannot guarantee the security of our systems or databases, nor can we guarantee that personal information we collect about you will not be breached, intercepted, destroyed, accessed, or otherwise disclosed without authorization. Accordingly, any information you transfer to or from INNOVATE1 Services Website is provided at your own risk.</p>
			<p>Please do your part to help us keep your information secure. You are responsible for maintaining the confidentiality of your password and Website Account, and are fully responsible for all activities that occur under your password or Website Account. INNOVATE1 Services specifically reserves the right to terminate your access to the INNOVATE1 Services Website and any contract you have with INNOVATE1 Services related to the INNOVATE1 Services Website in the event it learns or suspects you have disclosed your INNOVATE1 Services Website Account or password information to an unauthorized third party.</p>
		</div>
		<div class="text-row">
			<h4>Your rights</h4>
			<p>INNOVATE1 Services seeks to ensure all individuals are provided with the rights mandated by their governing jurisdiction. Not all of the rights discussed herein will apply to each individual data subject and may not apply to you depending upon your jurisdiction.</p>
			<p>You may benefit from a number of rights in relation to your information that we process. Some rights apply only in certain limited cases, depending on your location. If you would like to manage, change, limit, or delete your personal information, you can do so by contacting us. Upon request, INNOVATE1 Services will provide you with information about whether we hold any of your personal information.   In certain cases where we process your information, you may also have a right to restrict or limit the ways in which we use your personal information. In certain circumstances, you also have the right to request the deletion of your personal information, and to obtain a copy of your personal information in an easily accessible format.</p>
			<p>To the extent that such rights are mandated by the laws applicable to the individual data subject, such as the European Union General Data Protection Regulation ("GDPR"), the following rights may apply:  the right to access (GDPR, Article 15); the right to rectification (GDPR, Article16); the right to erasure (GDPR, Article 17); the right to restrict processing (GDPR, Articles 18); the right of object (GDPR, Article 21); and if applicable, the right to data portability (GDPR, Article 20). You may also have a right to lodge a complaint with an appropriate data privacy regulatory authority (GDPR, Article 77).</p>
			<p>If we process your information based on our legitimate interests as explained in this Privacy Policy, or in the public interest, you can object to this processing in certain circumstances. In such cases, we will cease processing your information unless we have compelling legitimate grounds to continue processing or where it is needed for legal reasons. Where we use your data for direct marketing purposes, you can always object using the unsubscribe link in such communications or changing your account settings.</p>
			<p>Where you have provided consent to certain data processing, you have the right to withdraw that consent at any time by contacting INNOVATE1 Services at: tmahoney@innovate1services.com. A withdrawal of consent will not affect the validity of our use of your personal data up until the point you have withdrawn your consent.</p>
		</div>
		<div class="text-row">
			<h4>Access and Updating Your Personal Information</h4>
			<p>INNOVATE1 Services welcomes you to contact us regarding the information we have collected about you, including regarding the nature and accuracy of the data that has been collected about you, to request an update, modification, or deletion of your information, to opt-out of certain INNOVATE1 Services Website uses of your information, or to withdraw any consent you may have granted to INNOVATE1 Services.</p>
			<p>Please note requests to delete or remove your information do not necessarily ensure complete or comprehensive removal of the content or information posted in all cases. These requests will be handled according to applicable laws and regulations. Please note that if you choose to delete your information or opt-out of the collection and use of your information, you understand that certain features, including but not limited to access to the INNOVATE1 Services Website or certain areas of the INNOVATE1 Services Website, may no longer be available to you.</p>
			<p>We may retain the information we receive about you for as long as necessary to fulfil our contractual and legal obligations, or indefinitely where required or permitted, but information generally will be retained only for as long as necessary to fulfil the purposes for which the information was collected, or as otherwise required by law. In addition, we may delete your personal data from our systems as part of a data retention plan.  Following termination or deactivation of a Website Account, INNOVATE1 Services may retain your information and content for a commercially reasonable time for backup, archival, and audit purposes.</p>
		</div>
		<div class="text-row">
			<h4>Do Not Track</h4>
			<p>INNOVATE1 Services does not currently employ a process for automatically responding to "Do Not Track" (DNT) signals sent by web browsers, mobile devices, or other mechanisms. Per industry standards, third parties may be able to collect information, including personal data, about your online activities over time and across different websites or online services when you use INNOVATE1 Services Website. You may opt out of online behavioral ads at <a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>. You also may limit certain tracking by disabling cookies in your web browser.</p>
		</div>
		<div class="text-row">
			<h4>Safely Using INNOVATE1 Services</h4>
			<p>Despite INNOVATE1 Services’ safety and privacy controls, we cannot guarantee the INNOVATE1 Services Website are entirely free of illegal, offensive, or otherwise inappropriate material, or that you will not encounter inappropriate or illegal conduct from other users when using the INNOVATE1 Services Website. INNOVATE1 Services shall not be liable for the content, accuracy, or up-to-date state of the information freely published by other users of the INNOVATE1 Services Website. You can help INNOVATE1 Services by notifying us of any unwelcome contact by contacting us using the contact information above.</p>
		</div>
		<div class="text-row">
			<h4>California Privacy Rights</h4>
			<p>To the extent that the laws of California apply to any INNOVATE1 Services customers, California residents may have the right to request certain information about our collection, use, and disclosure of their personal information as described in applicable laws such as the California Consumer Privacy Act ("CCPA").</p>
			<div><b>Access to Specific Information and Data Portability Rights</b></div>
			<p>California residents may have the right to request that we disclose the following information about our collection and use of personal information over the twelve months prior to your request:</p>
			<ul>
				<li>The categories of personal information we collect about you.</li>
				<li>The categories of sources for the personal information we collect about you.</li>
				<li>Our business or commercial purpose for collecting or selling that personal information.</li>
				<li>The categories of third parties with whom we share that personal information.</li>
				<li>The specific pieces of persona information collected about you.</li>
				<li>If we disclose your personal information for a business purpose, a list of the categories of personal information we have disclosed in the prior twelve months.</li>
				<li>If we sold your personal information for a business purpose, a list of the categories of personal information we have sold in the prior twelve months.</li>
			</ul>
			<div><b>Deletion Request Rights</b></div>
			<p>You may have the right to request that we delete any of your personal information that we collected from you and retained, subject to certain exceptions.  Once we receive and confirm your request, we will delete (and direct our service providers to delete) your personal information from our records, unless an exception applies.</p>
			<p>We may deny your deletion request if retaining the information is necessary for us or our service provider(s) to:</p>
			<ul>
				<li>Complete the transaction for which we collected the personal information, provide a good or service that you requested, take actions reasonably anticipated within the context of our ongoing business relationship with you, or otherwise perform our contract with you.</li>
				<li>Detect security incidents, protect against malicious, deceptive, fraudulent, or illegal activity, or prosecute those responsible for such activities.</li>
				<li>Debug products to identify and repair errors that impair existing intended functionality.</li>
				<li>Exercise free speech, ensure the right of another consumer to exercise their free speech rights, or exercise another right provided for by law.</li>
				<li>Comply with the California Electronic Communications Privacy Act (Cal. Penal Code § 1546 et. seq.).</li>
				<li>Engage in public or peer-reviewed scientific, historical, or statistical research in the public interest that adheres to all other applicable ethics and privacy laws, when the information’s deletion may likely render impossible or seriously impair the research’s achievement, if you previously provided informed consent.</li>
				<li>Enable solely internal uses that are reasonably aligned with consumer expectations based on your relationship with us.</li>
				<li>Comply with a legal obligation.</li>
				<li>Otherwise make other internal and lawful uses of that information that are compatible with the context in which you provided it.</li>
			</ul>
			<div><b>Exercising Access, Data Portability, and Deletion Rights</b></div>
			<p>To exercise the access, data portability, and deletion rights described above, please submit a request to us by either:</p>
			<ul>
				<li>Calling us at [TOLL-FREE Number];</li>
				<li>Visiting [WEBSITE ADDRESS]; or</li>
				<li>Writing us at: tmahoney@innovate1services.com with "Request for California Privacy Information" on the subject line and in the body of your message.</li>
			</ul>
			<p>You must provide enough information that we can reasonably verify you are a California resident about whom we collected personal information or are an authorized representative of such a person, and you must provide us with sufficient detail to allow us to property understand, evaluate, and respond to your request. We will only use personal information provided in these requests to verify the requestor’s identity or authority to make the request.</p>
			<p>Making a verifiable consumer request does not require you to create an account with us. However, we do consider requests made through your password protected account sufficiently verified when the request relates to personal information associated with that specific account.</p>
			<div><b>Response Timing and Format</b></div>
			<p>We endeavor to respond to a verifiable consumer request within forty-five (45) days of its receipt.  If we require more time, we will inform you of the reason and extension period in writing.</p>
			<p>If you have an account with us, we will deliver our written response to that account.  If you do not have an account with us, we will deliver our written response by mail or electronically, at your option.</p>
			<p>Any disclosures we provide will only cover the 12-month period preceding the verifiable consumer request’s receipt. The response we provide will also explain the reasons we cannot comply with a request, if applicable.  For data portability requests, we will select a format to provide your personal information that is readily useable and should allow you to transmit the information from one entity to another entity without hindrance.</p>
			<p>We do not charge a fee to process or respond to your verifiable consumer request unless it is excessive, repetitive, or manifestly unfounded.  If we determine that the request warrants a fee, we will tell you why we made that decision and provide you with a cost estimate before completing your request.</p>
			<div><b>Personal Information Sales Opt-Out and Opt-In Rights</b></div>
			<p>If you are 16 years of age or older, you have the right to direct us to not sell your personal information at any time (the "right to opt-out").  We do not sell the personal information of consumers we actually know are less than 16 years of age, unless we receive affirmative authorization (the "right to opt-in") from either the consumer who is between 13 and 16 years of age, or the parent or guardian of a consumer less than 13 years of age. Consumers who opt-in to personal information sales may opt-out of future sales at any time.</p>
			<p>To exercise the right to opt-out, you (or your authorized representative) may submit a request to us by sending an email to <a href="info@innovate1services.com">info@innovate1services.com</a></p>
			<p>Once you make an opt-out request, we will wait at least twelve (12) months before asking you to reauthorize personal information sales. However, you may change your mind and opt back in to personal information sales at any time by sending an email to<br><a href="info@innovate1services.com">info@innovate1services.com</a></p>
			<p>You do not need to create an account with us to exercise your opt-out rights. We will only use personal information provided in an opt-out request to review and comply with the request.</p>
			<div><b>Non-Discrimination</b></div>
			<p>We will not discriminate against you for exercising any of your CCPA rights. Unless permitted by the CCPA, we will not:</p>
			<ul>
				<li>Deny you goods or services.</li>
				<li>Charge you different prices or rates for goods or services, including through granting discounts or other benefits, or imposing penalties.</li>
				<li>Provide you a different level or quality of goods or services.</li>
				<li>Suggest that you may receive a different price or rate for goods or services or a different level or quality of goods or services.</li>
			</ul>
			<p>However, we may offer you certain financial incentives permitted by the CCPA that can result in different prices, rates, or quality levels.  Any CCPA-permitted financial incentive we offer will reasonably relate to your personal information’s value and contain written terms that describe the program’s material aspects. Participation in a financial incentive program requires your prior opt in consent, which you may revoke at any time.</p>
			<div><b>Changes to Our Privacy Policy</b></div>
			<p>INNOVATE1 Services may modify this Privacy Policy from time to time. The most current version of this Privacy Notice will govern our use of your information and will be located at <a href="https://www.innovate1services.com/cms/privacy">https://www.innovate1services.com/cms/privacy</a>. You may contact us to obtain prior versions. We will notify you of material changes to this policy by posting a notice at the INNOVATE1 Services Website or by emailing you at an email address associated with your Website Account, if applicable, and provide an "at a glance" overview of any changes.</p>
		</div>
	</div>
</section>
<!-- End body -->
<?php include 'footer.php';?>