<?php include 'header.php';?>
<!-- Start body -->
<section class="head-sec gradient-bg">
	<div class="container">
		<h1>Terms of Use</h1>
	</div>
</section>
<section class="section-setting">
	<div class="container" style="max-width: 1000px;">
		<div class="text-row">
			<p>These are the Terms of Use ("Terms") for INNOVATE1 Services which govern your access to and use of the INNOVATE1 Services Service (as defined below). Please note, your access to and use of the INNOVATE1 Services Service is conditioned on your acceptance of and compliance with these Terms. By accessing or using the INNOVATE1 Services Service, you agree you are bound by these Terms.</p>
		</div>
		<div class="text-row">
			<div class="highlight">
				<p>PLEASE READ THESE TERMS OF SERVICE CAREFULLY BEFORE ACCESSING OR USING THE INNOVATE1 SERVICES SERVICE AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, OBLIGATIONS, AND AVAILABLE REMEDIES RESULTING FROM YOUR USE OF THE SERVICES. THESE INCLUDE VARIOUS LIMITATIONS AND EXCLUSIONS, AS DESCRIBED BELOW. BY ACCESSING OR USING THE SERVICES, YOU AGREE YOU ARE BOUND BY THESE TERMS OF SERVICE IN THEIR ENTIERTY. IF YOU DO NOT AGREE TO ALL OF TERMS AND CONDITIONS INCLUDED WITHIN THESE TERMS, THEN YOU MAY NOT ACCESS OR USE THE SERVICES.</p>
			</div>
		</div>
		<div class="text-row">
			<h4>Definition of Terms</h4>
			<p><b>Commercial Transaction:</b> shall mean the commencement and/or completion of any Registration, Application Processing and/or Bill Presentment Transaction between INNOVATE1 Services and a customer for an authorized transfer of goods or services using the INNOVATE1 Services Service.</p> 
			<p><b>Customer/You:</b> shall mean any individual or corporation that completes a Registration or Application using the INNOVATE1 Services Service.</p>
			<p><b>INNOVATE1 Services or Company:</b> shall mean INNOVATE1 Services, and any subsidiaries and affiliates.</p>
			<p><b>INNOVATE1 Services Service:</b> shall mean the INNOVATE1 Services Service accessible via the INNOVATE1 Services Website.</p>
			<p><b>Payment Transaction:</b> shall mean a payment made for an INNOVATE1 Services Registration, Application and/or Bill Presentment Service.</p>
			<p><b>User:</b> shall mean any individual or entity that initiates a Commercial Transaction using the INNOVATE1 Services Service.</p>
			<p><b>User ID and Password:</b> shall mean a unique user identifier and password selected by users to access the INNOVATE1 Services Service via the Website.</p>
			<p><b>User Jurisdiction:</b> shall mean the territory from which a User or Operator is physically located upon initiating payment using the INNOVATE1 Services Service or on accessing the INNOVATE1 Services Website.</p>
		</div>
		<div class="text-row">
			<h4>Acceptance of the Terms</h4>
			<p>Please be aware that these Terms constitute a binding legal agreement between you and INNOVATE1 Services outlining your legal rights, obligations, and remedies arising from your use of the INNOVATE1 Services Service. You agree you are responsible for your use of the INNOVATE1 Services Service and any consequences resulting from your use of the INNOVATE1 Services Service. You may use the INNOVATE1 Services Service only in compliance with these Terms and all applicable local, state, national, and international laws, rules and regulations. If you do not agree to these Terms, you may not use the INNOVATE1 Services Service.</p>
			<p>You may use the Services only if you can form a binding contract with INNOVATE1 Services and are not a person barred from receiving services under the laws of the United States or other applicable jurisdictions. If you are accepting these Terms and using the INNOVATE1 Services Service on behalf of a company, organization, government, or other legal entity, you represent and warrant that you are authorized to do so and that you agree, on behalf of the party that you represent, to this agreement. If you reside in a jurisdiction that restricts the use of the INNOVATE1 Services Service because of age or restricts the ability to enter into agreements such as this one due to age, you must abide by such age limits, and you must not use the INNOVATE1 Services Service.</p>
			<p>By accessing or using the INNOVATE1 Services Service, you represent and warrant that you have the right, authority, and capacity to enter into this agreement, you will abide by these Terms, and that you have read, understand, and agree to be bound by these Terms, and by the terms of INNOVATE1 Services’ Privacy Policy available at <a href="https://www.innovate1services.com/cms/privacy">https://www.innovate1services.com/cms/privacy</a> incorporated into this agreement by this reference.</p>
		</div>
		<div class="text-row">
			<h4>Ability to Accept Terms of Use</h4>
			<p>The INNOVATE1 Services Service is intended for legal use by adults only and is not directed to individuals under the age of 18. You may not use the INNOVATE1 Services Service if you are under the age of 18, and any registration by anyone under 18 is void. By accessing or using the INNOVATE1 Services Service, and thereby agreeing to these Terms, you represent and warrant to us: (1) that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent; (2) you have not previously been suspended or removed from the INNOVATE1 Services Service; (3) are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms; and (4) that your use of the INNOVATE1 Services Service is in compliance with any and all applicable laws and regulations.</p>
		</div>
		<div class="text-row">
			<h4>Ability to Accept Terms of Use</h4>
			<p>The INNOVATE1 Services Service is intended for legal use by adults only and is not directed to individuals under the age of 18. You may not use the INNOVATE1 Services Service if you are under the age of 18, and any registration by anyone under 18 is void. By accessing or using the INNOVATE1 Services Service, and thereby agreeing to these Terms, you represent and warrant to us: (1) that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent; (2) you have not previously been suspended or removed from the INNOVATE1 Services Service; (3) are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms; and (4) that your use of the INNOVATE1 Services Service is in compliance with any and all applicable laws and regulations. </p>
		</div>
		<div class="text-row">
			<h4>Accounts & Registration</h4>
			<p><b>Registering for a INNOVATE1 Services Account:</b> In order to use or access certain Services or features of the INNOVATE1 Services Service, you may be asked to register for a user account (a "INNOVATE1 Services Account") and become a registered user of the INNOVATE1 Services Service (a "Registered User"). By becoming a Registered User, you agree to: (1) provide accurate, current, and complete information about yourself and/or the Registered User during the registration process; (2) maintain and promptly update such information to keep it accurate, current, and complete; (3) maintain the security of your password and login information, and not disclose your password or login information to any third party; (4) accept full responsibility for all use of any INNOVATE1 Services you register, and for any actions that arise from or take place using your INNOVATE1 Services Account, whether or not you have authorized such actions or use; and (5) immediately notify INNOVATE1 Services of any unauthorized use of your INNOVATE1 Services Account. Failure to abide by this Agreement constitutes a breach of these Terms, which may result in immediate termination of your INNOVATE1 Services Account.</p>
			<p><b>INNOVATE1 Services Account Information:</b>You may not select or use a INNOVATE1 Services Account name, handle, or login that: (1) is comprised of or includes the name of another person with the intent to impersonate that person; (2) is subject to any rights of a person other than you without appropriate authorization; (3) suggests a false association between you and INNOVATE1 Services; or (4) that, in INNOVATE1 Services’ sole discretion, is offensive, vulgar, or obscene. INNOVATE1 Services reserves the right to refuse registration of a INNOVATE1 Services Account, or cancel any account name, in its sole discretion. </p>
			<p><b>INNOVATE1 Services’ Access to the Services:</b> INNOVATE1 Services maintains the right to suspend or disable your access to the INNOVATE1 Services Service and any INNOVATE1 Services Account you may have created, or terminate these Terms, at its sole discretion and without prior notice to you if you breach the Terms, or if INNOVATE1 Services otherwise determines such action is warranted. INNOVATE1 Services reserves the right to revoke your access to and use of the INNOVATE1 Services Service at any time, with or without cause, whether or not you have established a INNOVATE1 Services Account or are a Registered User.</p>
			<p><b>Deleting INNOVATE1 Services Account:</b>You may delete and cancel your INNOVATE1 Services Account and your access to the INNOVATE1 Services Service at any time by contacting INNOVATE1 Services at the email address below and requesting that your account be deleted. Once you request account deletion, we will no longer store or use your information except as otherwise disclosed in our Privacy Policy. Please further note that certain information and content may persist for some time in caching, backup, and archival copies and in our internal records relating to use of our INNOVATE1 Services Service.</p>
		</div>
		<div class="text-row">
			<h4>User Conduct</h4>
			<p>As a condition of your use of the INNOVATE1 Services Service, you agree not to use the INNOVATE1 Services Service: (1) for any illegal purpose; (2) for any purpose that is prohibited by these Terms; or (3) for any other purpose not reasonably intended by INNOVATE1 Services as typical or expected use of the INNOVATE1 Services Service consistent with the purposes for which the INNOVATE1 Services Service were created. You specifically represent, warrant, and covenant that you will not do any of the following:</p>
			<ul>
				<li>Use the INNOVATE1 Services Service for or in connection with any illegal purpose, including any violation of any applicable local, state, national, or international law, or rule or regulation having the force of law;</li>
				<li>Abuse, harass, threaten, impersonate, or intimidate others;</li>
				<li>Post, upload, or otherwise distribute or post links to any content that is unlawful, defamatory, libellous, inaccurate, or that you do not have all necessary rights to transmit, or that INNOVATE1 Services or a reasonable person could deem to be objectionable, profane, indecent, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate as determined by INNOVATE1 Services in its sole discretion;</li>
				<li>Post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain any password or other confidential information, or private information from any User;</li> 
				<li>Use the INNOVATE1 Services Service to create or submit unwanted email ("Spam") to be sent to any other person or any URL;</li>
				<li>Submit content linking or otherwise directing others to affiliate programs, multi-level marketing schemes, or off-topic content;</li>
				<li>With the exception of accessing RSS feeds, to use any robot, spider, scraper or other automated means to access the INNOVATE1 Services Service for any purpose without our express written permission;</li>
				<li>Take any action that imposes, or may impose in our sole discretion an unreasonable or disproportionately large load on our infrastructure;</li>
				<li>Interfere or attempt to interfere with the proper working of the INNOVATE1 Services Service or any activities conducted on or through the INNOVATE1 Services Service;</li>
				<li>Bypass any measures we may use to prevent or restrict access to the INNOVATE1 Services Service or any part of the INNOVATE1 Services Service;</li>
				<li>Interfere with the operation of the INNOVATE1 Services Service or any User’s enjoyment of the INNOVATE1 Services Service, including without limitation, by: (i) uploading or otherwise disseminating viruses, adware, spyware, worms, or other malicious software or code; (ii) making unsolicited offers, advertisements, or other solicitations, directing spam or other unsolicited communications to other Users, or conducting your own contests or promotions using the INNOVATE1 Services Service; (iii) attempting to collect personal information about Users or third parties without their consent; or (iv) interfering with or disrupting any networks, equipment, or servers connected to or used to provide the INNOVATE1 Services Service, or violating the regulations, policies, or procedures of such networks, equipment, or servers;</li> 
				<li>Share, sell, or otherwise transfer the access granted to you to the INNOVATE1 Services Service, including information regarding your INNOVATE1 Services Service login information, or password, or otherwise permit any other person to access the INNOVATE1 Services Service using your information, login, or password (excluding invitations to join the INNOVATE1 Services Service that you send to others);</li>
				<li>Use the INNOVATE1 Services Service, related content, or any component thereof, for any commercial purposes unintended by INNOVATE1 Services, including advertising, offering for sale, or selling any item using the INNOVATE1 Services Service;</li>
				<li>Violate, or encourage others to violate, the rights of third parties, including by infringing or misappropriating third party Intellectual Property or other legal rights;</li>
				<li>Reproduce, distribute, publicly display or perform, modify, make derivative works of, redistribute, sublicense, rent, publish, sell, assign, lease, market, transfer, or otherwise make the INNOVATE1 Services Service, code or program, available to others, in whole or part, without ownership of or all appropriate rights in such content;</li>
				<li>Interfere with security features of the INNOVATE1 Services Service, including without limitation, by: (i) disabling or circumventing features that prevent or limit use or copying of content, or which violate copyrighted or otherwise legally protected software; or (ii) reverse engineering or otherwise attempting to extract the source code of the INNOVATE1 Services Service or any part thereof, except to the extent that such activity is expressly permitted by applicable law;</li>
				<li>Perform any fraudulent activity using or in connection with the INNOVATE1 Services Service, including impersonating any person or entity, claiming false affiliations, accessing the accounts or passwords of others without permission, or falsifying your age, date of birth, or contact information; or</li>
				<li>Attempt to do any of the foregoing in this Section, or assist or permit any persons in engaging in any of the activities described in this Section.</li>
			</ul>
		</div>
		<div class="text-row">
			<h4>Processing of Payment Transactions </h4>
			<p>The INNOVATE1 Services Service facilitates the processing of transactions for which payment is made ("Payment Transactions"). The Service will automate Payment Transactions through the appropriate Credit/Debit Card Network and/or financial institutions. INNOVATE1 Services reserves the right to delay or stop the payment processing of transactions that may be dubious, fraudulent, or are a violation of the INNOVATE1 Services Terms of Use or Privacy Policy or a violation of existing laws.</p>
		</div>
		<div class="text-row">
			<h4>Third Party Sites</h4>
			<p>INNOVATE1 Services may employ third-party advertising and marketing to deliver ads, information, and other promotions to you outside of the INNOVATE1 Services Service, such as on third-party websites or platforms. By agreeing to our Terms, you agree to receive such advertising and marketing from INNOVATE1 Services. INNOVATE1 Services may compile and release information regarding you and your use of the INNOVATE1 Services Service on an anonymous basis as part of a customer profile or similar report or analysis in compliance with our Privacy Policy and applicable laws.</p>
			<p>The INNOVATE1 Services Service may contain links to third-party websites or resources. You acknowledge and agree that INNOVATE1 Services shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.</p>
		</div>
		<div class="text-row">
			<h4>Electronic Communications Usage and Notices</h4>
			<p>As part of your use of the INNOVATE1 Services Service, you may be asked to elect to receive certain email notifications from INNOVATE1 Services and its partners. These messages may include event updates and other promotions. Your election to receive such messages represents your express written consent to receiving emails from INNOVATE1 Services related to the INNOVATE1 Services Service. You may opt out of receiving certain notifications in association with the INNOVATE1 Services Service by completing the opt-out process provided to you with each email message. By opting-out of receiving notifications, you understand that we may not be able to communicate important information to you. Please note we may still contact you regarding certain important INNOVATE1 Services Service announcements or notifications even if you have opted-out from other messages.</p>
			<p>You consent to receive from INNOVATE1 Services all communications, including notices, agreements, legally required disclosures or other information in connection with the INNOVATE1 Services Service (collectively, "Notices") electronically. INNOVATE1 Services may provide such Notices by posting them on or within the INNOVATE1 Services Service, by electronic mail to your email address on record in INNOVATE1 Services Account information, or by written communication sent by first class mail or pre-paid post to your address on record. You agree that we may communicate with you regarding INNOVATE1 Services and other entities by electronic means to your mobile device and that certain information about your usage of the INNOVATE1 Services Service may be communicated to us. In the event you change or deactivate your mobile device, you agree to promptly update your information to ensure that your messages are not sent to the person that acquires your old device.</p>
		</div>
		<div class="text-row">
			<h4>Cancelation & Refunds</h4>
			<p>Cancelation & Refund Policy for Users can be found on the INNOVATE1 Services Website.</p>
		</div>
		<div class="text-row">
			<h4>INNOVATE1 Services Service and Functions</h4>
			<p>INNOVATE1 Services business is to provide the automation of online registration, application and bill presentment processes ONLY. INNOVATE1 Services does not issue Passports or Visas. INNOVATE1 Services does not determine applicant’s qualification to receive a Passport or Visa.  INNOVATE1 Services does not guarantee that a User shall be granted an Interview by an Embassy, Consulate or High Commission.</p>
			<p>Since the service is limited to online transactions, INNOVATE1 Services does not qualify as a financial institution and monies held by INNOVATE1 Services shall not be deemed as deposits nor are they insured to benefit the customer by the Federal Deposit Insurance Corporation or any governmental agency.</p>
			<p>INNOVATE1 Services does not guarantee the identity of any User.</p>
		</div>
		<div class="text-row">
			<h4>Taxes for Customers</h4>
			<p>INNOVATE1 Services shall not be responsible for any User taxes, which arise as a result of the INNOVATE1 Services usage. User herein accept to cooperate with all applicable tax laws, of the reporting and payment of any taxes, which are related to your INNOVATE1 Services Payment Transactions.</p>
		</div>
		<div class="text-row">
			<h4>Unclaimed Property</h4>
			<p>In certain circumstances, while using INNOVATE1 Services, INNOVATE1 Services may hold your funds while an issue is being resolved.</p>
			<p>We will make every effort to contact You using your contact details in our records. However, if we are unable to reach You and/or have no report of your INNOVATE1 Services usage for more than three years, such unclaimed funds will be deemed to be Unclaimed Property by provision of applicable law.</p> 
			<p>We reserve the right to deduct a dormancy fee or other administrative charges from such unclaimed funds, as permitted by applicable law.</p>
		</div>
		<div class="text-row">
			<h4>Export Control</h4>
			<p>You agree to comply fully with all U.S. and foreign export laws and regulations to ensure that neither the INNOVATE1 Services Service, nor any technical data related thereto, nor any direct product thereof, is exported or re-exported directly or indirectly in violation of, or used for any purposes prohibited by, such laws and regulations. By using the INNOVATE1 Services Service, you represent and warrant that: (1) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country; and (2) you are not listed on any U.S. Government list of prohibited or restricted parties.</p>
		</div>
		<div class="text-row">
			<h4>International Use</h4>
			<p>The INNOVATE1 Services Service are controlled and operated by INNOVATE1 Services from within the United States. INNOVATE1 Services makes no representations that materials contained within the INNOVATE1 Services Service are appropriate or available for use in other locations, and access to the INNOVATE1 Services Service from locations where such activity is illegal is prohibited. Those who choose to use the INNOVATE1 Services Service from other locations do so of their own initiative and are solely responsible for compliance with all applicable laws.</p>
		</div>
		<div class="text-row">
			<h4>Termination</h4>
			<p>INNOVATE1 Services may change, suspend or discontinue the INNOVATE1 Services Service for any reason, at any time, including the availability of any INNOVATE1 Services Service, features, or content, without notice to you. INNOVATE1 Services may also impose limits on certain services, features, or content, or restrict your access to parts or all of the INNOVATE1 Services Service with or without notice to you.</p>
			<p>INNOVATE1 Services may also terminate or suspend your use of or access to the INNOVATE1 Services Service at any time, immediately, without notice, and without refund, for any violation of these Terms, in our sole and absolute discretion. Upon such termination or suspension, you must immediately cease accessing or using the INNOVATE1 Services Service, and agree not to access, re-download, re-register or otherwise make use of, or attempt to use, the INNOVATE1 Services Service.</p>
			<p>INNOVATE1 Services may also remove or disable access to any content and suspend or ban your access to the INNOVATE1 Services Service or any INNOVATE1 Services Account at any time for any violation of these Terms, including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such content. To report violations of the Terms, please contact INNOVATE1 Services using the information below. You are solely responsible for your interactions with other Users of the INNOVATE1 Services Service. INNOVATE1 Services reserves the right but has no obligation, to monitor disputes between you and other Users.</p>
			<p>You acknowledge that we reserve the right to take action, technical, legal, or otherwise, to block, nullify, or deny your ability to access the INNOVATE1 Services Service. You understand that we may exercise this right in our sole discretion, and this right shall be in addition to and not in substitution for any other rights and remedies otherwise available to INNOVATE1 Services. Continued use of the INNOVATE1 Services Service, its components, databases, or documentation, or any part thereof, after termination is a breach of the terms of this Agreement and a violation of copyright laws. You acknowledge that we may disable access to, refuse to post, or modify or remove any information or content, in whole or in part, for any reason or no reason at all. All provisions of this Agreement, which by their nature should survive termination, shall survive the termination of this Agreement, including, without limitation, provisions regarding ownership, warranty disclaimers, indemnity, and limitations of liability.</p>
		</div>
		<div class="text-row">
			<h4>Indemnification</h4>
			<p>You shall indemnify and hold harmless INNOVATE1 Services its subsidiaries, affiliates, successors or assigns and their respective directors, officers, shareholders, and employees against any and all loss, injury, death, damage, liability, claim, deficiency, action, judgment, interest, award, penalty, fine, cost or expense, including reasonable attorney and professional fees and costs, and the cost of enforcing any right to indemnification hereunder and the cost of pursuing any insurance providers arising out of or related to the INNOVATE1 Services Service, use of the INNOVATE1 Services Service, violation of the Terms, or the infringement by you of any Intellectual Property, or violation of any right of any person or entity by you or any third party using your information, login, or password.</p>
		</div>
		<div class="text-row">
			<h4>Disclaimer</h4>
			<p>You acknowledge that INNOVATE1 Services has no control over, and no duty to take any action regarding: (1) which Users gain access to the INNOVATE1 Services Service; (2) what effects the INNOVATE1 Services Service may have on you; (3) how you may interpret or use the INNOVATE1 Services Service; or (4) what actions you may take as a result of having been exposed to the INNOVATE1 Services Service.</p> 
			<p>The Services may contain, or direct you to sites containing, information that some people may find offensive or inappropriate. INNOVATE1 Services makes no representations concerning any content contained in or accessed through the INNOVATE1 Services Service, and INNOVATE1 Services will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the INNOVATE1 Services Service. INNOVATE1 Services makes no guarantee or warranty, express or implied, as to the reliability, accuracy, timeliness or completeness of that information and assumes no responsibility for any errors or omissions therein. INNOVATE1 Services cannot guarantee that you will obtain the results you seek or warrant that INNOVATE1 Services Service will be error-free. INNOVATE1 Services makes no representation or warranty of any kind with respect to the use of INNOVATE1 Services Service or the use or accuracy of the information on the INNOVATE1 Services Service.</p>
			<p>USER ACCESSES THE INNOVATE1 SERVICES SERVICE AT HIS OR HER OWN RISK. THE INNOVATE1 SERVICES SERVICE IS PROVIDED ON AN "AS IS, AS AVAILABLE" BASIS WITHOUT WARRANTY OF ANY KIND WHETHER EXPRESS, IMPLIED, OR STATUTORY, AS TO THE DESCRIPTION, QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR COMPLETENESS OF ANY SERVICES PROVIDED HEREUNDER OR DESCRIBED HEREIN, OR AS TO ANY OTHER MATTER, ALL OF WHICH WARRANTIES BY INNOVATE1 SERVICES ARE HEREBY DISCLAIMED. NEITHER INNOVATE1 SERVICES NOR ANY PARENT COMPANIES, SUBSIDIARIES, AFFILIATES, LICENSORS, EMPLOYEES OR AGENTS WARRANT THAT THE INNOVATE1 SERVICES SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE AND NO WARRANTY IS MADE AS TO THE RESULTS TO BE OBTAINED FROM USE OF THE INNOVATE1 SERVICES SERVICE. THIS DISCLAIMER IS APPLICABLE TO ANY DAMAGE OR INJURY RESULTING FROM NEGLIGENCE OR OMISSION OF INNOVATE1 SERVICES, COMPUTER VIRUS OR OTHER SIMILAR ITEM, TELECOMMUNICATIONS ERRORS, OR UNAUTHORIZED ACCESS TO OR USE OF USER INFORMATION THROUGH THEFT OR ANY OTHER MEANS. IN NO EVENT WILL INNOVATE1 SERVICES OR ANY OF ITS AFFILIATES, AGENTS, EMPLOYEES, ASSIGNS OR THIRD-PARTY CONTENT PROVIDERS BE HELD LIABLE FOR ANY CRIMINAL, TORTIOUS, OR NEGLIGENT ACTIONS OR OMISSIONS, OR ILLEGAL CONDUCT OF USERS OF THE INNOVATE1 SERVICES SERVICE.</p>
		</div>
		<div class="text-row">
			<h4>Limitations of Liability</h4>
			<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EXCEPT TO THE EXTENT THAT ANY EXCLUSION OR LIMITATION OF ITS LIABILITY IS VOID, PROHIBITED OR UNENFORCEABLE BY APPLICABLE LAW, NEITHER INNOVATE1 SERVICES NOR ITS AFFILIATES, EMPLOYEES, AGENTS OR THIRD-PARTY CONTENT PROVIDERS SHALL BE LIABLE FOR ANY LOSS RESULTING FROM USE OR UNAVAILABILITY OF INFORMATION OR CONTENT ON THE INNOVATE1 SERVICES SERVICE, INCLUDING BUT NOT LIMITED TO, ANY LOST PROFITS, LOSS OF REVENUE, LOSS OF USE, LOSS OF OR DAMAGE TO DATA OR INFORMATION OF ANY KIND, DAMAGE TO EQUIPMENT, HARDWARE OR OTHER PROPERTY OF USER, PERSONAL INJURY, OR ANY INDIRECT, SPECIAL, CONSEQUENTIAL, COMPENSATORY OR INCIDENTAL DAMAGES (WHETHER THE CLAIM IS BASED UPON BREACH OF CONTRACT, BREACH OF WARRANTY, STRICT LIABILITY, NEGLIGENCE, TORT OR OTHER LEGAL THEORY) ARISING OUT OF THIS AGREEMENT OR IN CONNECTION WITH USE OF THE INNOVATE1 SERVICES SERVICE OR CONTENT, OR FOR ANY DIRECT DAMAGES IN EXCESS OF $100 (IN THE AGGREGATE), EVEN IF THEY HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
			<p>The "Disclaimer" and "Limitation of Liability" provisions of this Agreement are for the benefit of INNOVATE1 Services as defined herein, and each of these individuals or entities shall have the right to assert and enforce these provisions directly against you on its own behalf.</p>
		</div>
		<div class="text-row">
			<h4>Governing Law</h4>
			<p>These Terms and any action related thereto will be governed by the laws of the State of New York without regard to or application of its conflict of law provisions or your state or country of residence. All claims, legal proceedings or litigation arising in connection with the INNOVATE1 Services Service will be brought solely in the federal or state courts located in New York, United States, and you consent to the jurisdiction of and venue in such courts and waive any objection as to inconvenient forum. Neither the United Nations Convention on Contracts for the International Sale of Goods nor any enactment of the Uniform Computer Information Transactions Act shall apply to this Agreement.</p>
			<p>Any claim under these Terms of Use must be brought within one (1) year after the cause of action arises, or such claim or cause of action is barred. No recovery may be sought or received for damages other than out-of-pocket expenses.</p>
			<p>In the event of any controversy or dispute between INNOVATE1 Services and You arising out of or in connection with your use of the Website, the parties shall attempt, promptly and in good faith, to resolve any such dispute. If we are unable to resolve any such dispute within a reasonable time (not to exceed sixty (60) days), then either party may submit a dispute arising out of or relating to these Terms of Use for arbitration in accordance with the rules and procedures of American Arbitration Association in effect at that time in a proceeding to be conducted in New York and the decision rendered in connection therewith will be binding on the parties hereto, provided, however, that nothing contained in this section shall restrict or limit the right of either party to seek injunctive relief from a court of competent jurisdiction.</p>
		</div>
		<div class="text-row">
			<h4>Assignment</h4>
			<p>This Agreement and the rights and obligations hereunder may not be assigned, in whole or in part, by you without the written consent of INNOVATE1 Services. INNOVATE1 Services may assign this Agreement upon ten (10) days prior written notice to you provided via email (if available) and by posting notice to the INNOVATE1 Services Service. This Agreement shall be binding upon, and inure to the benefit of, the successors, representatives and permitted assigns of the parties hereto.</p>
		</div>
		<div class="text-row">
			<h4>Intellectual Property</h4>
			<p>INNOVATE1 Services and its licensors and partners own all rights, titles, and interests in and to the INNOVATE1 Services Service, and all related Intellectual Property rights, including all registered and unregistered trademarks, trade dress, graphics, logos, designs, page headers, button icons, scripts, service names, software code, inventions, copyrights, and copyrightable works, and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Services (collectively, the "INNOVATE1 Services IP"). The INNOVATE1 Services IP may not be used in connection with any product or service in any manner that is likely to cause confusion or otherwise violate the rights granted to us in the INNOVATE1 Services IP, including use of any the INNOVATE1 Services IP as part of third-party trademarks, trade dress, and/or as part of domain names, email addresses, account names or handles, or other digital properties.</p>
			<p>This Agreement is not a sale and does not convey to you any rights of ownership in or related to the INNOVATE1 Services Service, or any Intellectual Property rights owned by INNOVATE1 Services. The INNOVATE1 Services name, the INNOVATE1 Services logos, and designs, and the product and service names associated with the INNOVATE1 Services Service are trademarks of INNOVATE1 Services or its affiliated third parties, and no right or license is granted to you by this Agreement to use INNOVATE1 Services IP for purposes not directly related to your use of the INNOVATE1 Services Service.</p>
		</div>
		<div class="text-row">
			<h4>Miscellaneous</h4>
			<div><b>Entire Agreement</b></div>
			<p>The Terms, including the incorporated INNOVATE1 Services Privacy Policy, constitutes the entire agreement between Users of the INNOVATE1 Services Service and INNOVATE1 Services regarding Users’ use of and access to the INNOVATE1 Services Service. Your use of the INNOVATE1 Services Service is intended for your enjoyment and benefit and the provision of the INNOVATE1 Services Service to you constitutes the sole and sufficient consideration that you are entitled to receive for any content or other contributions you have made to the INNOVATE1 Services Service.</p>
			<div><b>Waiver & Severability</b></div>
			<p>The failure of INNOVATE1 Services to enforce any right or provision of these Terms will not be deemed a waiver of such right or provision. In the event that any provision of these Terms is held to be invalid or unenforceable, then that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions of these Terms will remain in full force and effect.</p>
			<div><b>No Independent Contractor or Joint Venture</b></div>
			<p>The parties shall be independent contractors under this Agreement, and nothing herein will constitute either party as the employer, employee, agent or representative of the other party, or both parties as joint venturers or partners for any purpose.</p>
		</div>
		<div class="text-row">
			<h4>Changes to the Terms of Use</h4>
			<p>INNOVATE1 Services may modify these Terms from time to time. The most current version of these Terms will govern your use of the INNOVATE1 Services Service and will be located at <a href="https://www.innovate1services.com/cms/termsOfUse">https://www.innovate1services.com/cms/termsOfUse</a>. We will notify you of material changes to these Terms by posting a notice at the INNOVATE1 Services Service. By continuing to access or use the INNOVATE1 Services Service after those changes become effective, you agree to be bound by the revised Terms.</p>
		</div>
		<div class="text-row">
			<h4>Contacting INNOVATE1 SERVICES</h4>
			<p>Should you have any comments or questions about how we collect and use your personal information, communications can be directed to INNOVATE1 Services postal address, via email to <a href="mailto:info@innovate1services.com">info@innovate1services.com</a>.</p>
		</div>
	</div>
</section>
<!-- End body -->
<?php include 'footer.php';?>